### ISSUE TITLE
KeyError: 'getpwnam(): name not found: minidns'

### ISSUE THREAD

**Issue by prologic** [yaybu/minidns#8]
Trying to test out the latest development version:

```
#!python
(minidns)
XXXXXXXX@031986
Wed Feb 05 14:42:46
~/minidns
$ minidns -c example.conf start
Unhandled Error
Traceback (most recent call last):
  File "/Users/XXXXXXXX/.virtualenvs/minidns/lib/python2.7/site-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/Users/XXXXXXXX/.virtualenvs/minidns/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/Users/XXXXXXXX/.virtualenvs/minidns/lib/python2.7/site-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/Users/XXXXXXXX/.virtualenvs/minidns/lib/python2.7/site-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/Users/XXXXXXXX/.virtualenvs/minidns/lib/python2.7/site-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/Users/XXXXXXXX/.virtualenvs/minidns/lib/python2.7/site-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/Users/XXXXXXXX/.virtualenvs/minidns/lib/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/Users/XXXXXXXX/work/minidns/minidns/scripts/minidns.tac", line 26, in <module>
    OrchestrationService(conf).setServiceParent(application)
  File "/Users/XXXXXXXX/work/minidns/minidns/orchestra.py", line 17, in __init__
    self.dnsserver = DNSService(conf)
  File "/Users/XXXXXXXX/work/minidns/minidns/dns.py", line 297, in __init__
    self.factory = MiniDNSServerFactory(forwarders, savedir, self.get_ent())
  File "/Users/XXXXXXXX/work/minidns/minidns/dns.py", line 325, in get_ent
    ent = pwd.getpwnam(self.conf['user'])
exceptions.KeyError: 'getpwnam(): name not found: minidns'

Failed to load application: 'getpwnam(): name not found: minidns'
```

**Comment by winjer** [comment]
now listens on 53 by default, and the minidns user is created as part of packaging. must be run as root, but should definitely drop privs.
