### ISSUE TITLE
cannot provide config file

### ISSUE THREAD

**Issue by maasg** [yaybu/minidns#9]
Hi,

I'm attempting to configure minidns with a config file but when I provide the -c <file> option minidns fails with the following msg:

```python
root@db2ff248aa02:~# minidns  -c /root/config.txt start
Traceback (most recent call last):
  File "/usr/local/bin/minidns", line 9, in <module>
    load_entry_point('minidns==0.3', 'console_scripts', 'minidns')()
  File "/usr/local/lib/python2.7/dist-packages/minidns/scripts/server.py", line 191, in run
    client.start()
  File "/usr/local/lib/python2.7/dist-packages/minidns/scripts/server.py", line 75, in start
    os.environ["MINIDNS_CONFIG_FILE"] = opts.config
NameError: global name 'opts' is not defined
```
Is it something I'm doing wrong? Or is it a bug? Seems unlikely for something common as a config file.

**Comment by winjer** [comment]
this was a bug, and has been fixed.

**Comment by maasg** [comment]
@winjer  Awesome!
